#ifndef LIBREECHO_DIAGNOSTIC_PROTOCOL_H
#define LIBREECHO_DIAGNOSTIC_PROTOCOL_H

/* Big-endian dword protocol carried over the existing BROM USB data channel. */
#define DIAG_PROTOCOL_VERSION 1
#define DIAG_READY_MAGIC 0x4C454431
#define DIAG_REQUEST_MAGIC 0x4C455251
#define DIAG_RESPONSE_MAGIC 0x4C455250

#define DIAG_CMD_HELLO 0x9000
#define DIAG_CMD_READ_DEFAULT_SECTOR0 0x9001

#define DIAG_RESPONSE_WORDS 8
#define DIAG_INIT_REPORT_WORDS 11
#define DIAG_PARTITION_UNKNOWN 0xFFFFFFFF

#endif
